Table styles {
    id int [pk, increment]
    style varchar
    price decimal
}

Table sizes {
    id int [pk, increment]
    carets decimal
    price decimal
}

Table metals {
    id int [pk, increment]
    metal varchar
    price decimal
}

Table orders {
    id int [pk, increment]
    styleId int [ref: > styles.id]
    sizeId int [ref: > sizes.id]
    metalId int [ref: > metals.id]
}

Ref: orders.styleId > styles.id
Ref: orders.sizeId > sizes.id
Ref: orders.metalId > metals.id